### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by yeoniii20** [yeoniii20/Java#3]
# Todo 🚀
> controller 학습을 목적으로 한다.

### settings ⚙️
- [x] spring Initializr으로 초기 세팅하기

### Controller🌴
- [x] controller 생성하기
- [x] 서버 실행시켜서 html 파일 띄우기
- [x] controller에서 메세지 전달 -> html에서 확인하기

### questions 📢
1️⃣ Controller가 무엇인가
2️⃣ Spring Boots가 무엇인가
