### ISSUE TITLE
[Pratice2] Rest API

### ISSUE THREAD

**Issue by yeoniii20** [yeoniii20/Java#5]
# Todo 🐣
> Rest API를 학습하는 것을 목표로 한다.

### step1🌴
- [x]  `api Controller` 생성 및 실행

### step2 🪐
> 코드의 역할을 분리하여 유지보수에 유리하도록 한다.
- [x] 비지니스 로직을 `Controller`에서 분리하여 `Service` 계층 생성

### step3 ⚙️
> SPA(Spring Data JPA)를 사용해 ORM(Object-Relational Mapping)을 통해 객체를 DB 테이블에 매핑할 수 있도록 한다.
- [ ] Database 연동 (저장 및 불러오기)

### step4 🚀
> 사용자 정보를 생성(Create), 읽기(Read), 수정(Update), 삭제(Delete)하는 기본 CRUD API를 완성한다.
- [x] CRUD 기능 추가하기

### step5 🚛
>  클라이언트 요청을 검증하고, 오류 발생 시 적절한 예외를 처리하여 사용자에게 메시지를 제공한다.
- [ ] 예외 처리 및 검증

### step6 🍘
>   API 문서를 자동으로 생성하여, API 사용 방법을 쉽게 확인할 수 있도록 한다.
- [x] API 문서화 (Swagger 사용)
http://localhost:8080/swagger-ui/index.html#/

### questions 📢
1️⃣
2️⃣
